# Generated by Django 3.0.5 on 2024-05-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.BigIntegerField()),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.AlterModelTable(
            name='pet',
            table='pet',
        ),
    ]
