# Generated by Django 3.0.5 on 2024-06-13 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentstatus', models.CharField(default='pending', max_length=20)),
                ('transactionid', models.CharField(max_length=200)),
                ('paymentmode', models.CharField(default='paypal', max_length=50)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.customer')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.order')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='orderdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.CharField(max_length=100)),
                ('quantity', models.BigIntegerField()),
                ('totalprice', models.BigIntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.customer')),
                ('paymentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.payment')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet')),
            ],
            options={
                'db_table': 'orderdetail',
            },
        ),
    ]
