# Generated by Django 3.0.5 on 2024-06-20 06:10

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_orderdetail_payment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pet',
            managers=[
                ('cpetobj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
